print(hex(12))
print(bin(1))
print(2**4)
print(pow(2,4,3))
print(abs(-3))
print(abs(2))
print(round(3))
print(round(3.5))
print(round(3.9))
print(round(3.141, 2))
s = "Hello World"
print(s.center(20, 'z'))
print("Hello\thi")
print("Hello\thi".expandtabs())
print(s.isalnum())
print(s.isalpha())

#set
st = set()
st.add(1)
st.add(2)
st.add(3)

stc = st.copy()
st.add(4)
print(st, stc)
print(st.difference(stc))
#print(st.difference_update(stc))
print(st)
#print(st.discard(4))
print(st)
print(st.intersection(stc))
print(st.intersection(stc))
std = {5}
print(st.isdisjoint(stc))
print(st.isdisjoint(std))
print(stc.issubset(st))
print(st.issuperset(stc))
print(st.symmetric_difference(stc))
print(st.union(stc))
print(st.update(stc))
print(st, stc)

d = {'k1': 1, 'k2':2}
print({x:x**2 for x in range(10)})
print({k:v**2 for k, v in zip(['a', 'b'], range(2))})

l = [1,2,3]
print(l.append(4))
print(l.count(10))
print(l.count(1))
print(l.insert(0, -1))

b = [5,6]
print(l.extend(b))
print(l)
print(l.append(b))
print(l.pop())
print(l)
print(l.pop(0))
print(l)
print(l.remove(2))
print(l)
print(l.reverse())
print(l)
print(l.sort())
print(l)
